services:
  # PostgreSQL database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_pass
      POSTGRES_DB: mlflowdb
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow
    depends_on:
      - postgres


volumes:
  # minio-data:
  mlflow-data:
  postgres-data: