services:
  # mlflow server
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow

volumes:
  # volume to persist mlflow data, like experiments and artifacts
  mlflow-data:
    name: mlflow-data
