services:
  # mlflow server
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow


volumes:
  # minio-data:
  mlflow-data:
    name: mlflow-data