FROM python:3.10-slim 

WORKDIR /mlflow 

RUN pip install mlflow psycopg2-binary

ENV BACKEND_URI postgresql://mlflow_user:mlflow_pass@postgres:5432/mlflowdb

EXPOSE 5000 

CMD mlflow ui --backend-store-uri $BACKEND_URI --host 0.0.0.0